FROM osrf/ros:humble-desktop-full

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    wget \
    curl \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb && \
    dpkg -i cuda-keyring_1.1-1_all.deb && \
    apt-get update

RUN apt-get install -y \
    ros-humble-rosbag2-storage-mcap \
    ros-humble-tf-transformations \
    ros-humble-vision-msgs-rviz-plugins \
    cuda-libraries-12-3 \
    cudnn9-cuda-12 \
    python3-pip

RUN pip3 install \
    onnxruntime-gpu \
    numpy==1.23.5

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
RUN mkdir -p auto_drive models scene_records inference_records config

ENV PATH=/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
ENV CUDA_HOME=/usr/local/cuda

ENV DEBIAN_FRONTEND=

CMD ["tail", "-f", "/dev/null"]
